version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root3607
    ports:
    - "3306:3306"
    volumes:
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    - product:/var/lib/mysql
    
volumes:
  product:
  init.sql: