version: "3.8"
services:
  db:
    image: mysql
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: gerenciaconsultas
    ports:
    - "3306:3306"
    volumes:
    - mysql:/var/lib/mysql
    
volumes:
  mysql: